name: Test

on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ${{ matrix.os }}
    name: Test
    strategy:
      matrix:
        python-version: [ 3.4 ]
        os: [ windows-latest ]
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        run: |
           pip install --upgrade setuptools
           pip install psutil
            
