name: Test Nodejs Client with server

on:
  workflow_dispatch:
    inputs:
      client_tag:
        description: Client of the tag to test, starts with v
        required: true
        default: v4.0.0
      server_version:
        description: Server version
        required: true
        default: 4.1.4
      server_kind:
        description: Server kind, os or enterprise
        required: true
        default: os
jobs:
  test_nodejs_client:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    name: Test Node.js client ${{ github.event.inputs.client_tag }} with ${{ github.event.inputs.server_version }} server
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Download JARs
        run: python download_server_jars.py --version ${{ github.event.inputs.server_version }} --server-kind ${{ github.event.inputs.server_kind }} --dst jars
      - name: Checkout to master
        uses: actions/checkout@v2
        with:
          repository: hazelcast/hazelcast-nodejs-client
          path: master
          ref: master
      - name: Checkout to tag
        uses: actions/checkout@v2
        with:
          repository: hazelcast/hazelcast-nodejs-client
          path: tag
          ref: ${{ github.event.inputs.client_tag }}
      - name: Install dependencies and compile client
        run: |
          npm install
          npm run compile
        working-directory: tag
      - name: Install test dependencies
        run: |
          npm install
        working-directory: master
      - name: Copy client code into master
        run: |
          rm -rf $GITHUB_WORKSPACE/master/lib
          rm $GITHUB_WORKSPACE/master/package.json
          cp -a $GITHUB_WORKSPACE/tag/lib $GITHUB_WORKSPACE/master/lib
          cp -a $GITHUB_WORKSPACE/tag/package.json $GITHUB_WORKSPACE/master/package.json
      - name: Start RC
        env:
          HAZELCAST_ENTERPRISE_KEY: ${{ secrets.HAZELCAST_ENTERPRISE_KEY }}
        run: python start_rc.py --rc-version '0.8-SNAPSHOT' --jars jars --server-kind ${{ github.event.inputs.server_kind }} --use-simple-server
      - name: Run non-enterprise tests
        if: ${{ github.event.inputs.server_kind == 'os' }}
        run: node node_modules/mocha/bin/mocha --recursive test/integration/backward_compatible
        working-directory: master
      - name: Run all tests
        if: ${{ github.event.inputs.server_kind == 'enterprise' }}
        run: node node_modules/mocha/bin/mocha --recursive test/integration/backward_compatible
        working-directory: master
        env:
          HAZELCAST_ENTERPRISE_KEY: ${{ secrets.HAZELCAST_ENTERPRISE_KEY }}
